service: uroman-api

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024  # Increased memory for data loading
  timeout: 30       # Increased timeout for cold starts

functions:
  romanize:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: romanize
          method: post
          cors: true
    environment:
      PYTHONPATH: /var/runtime:/var/task:/var/task/lib

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
    slim: true
    strip: false
    slimPatternsAppendDefaults: false
    slimPatterns:
      - "**/*.pyc"
      - "**/__pycache__"
